exclude: '^$'
fail_fast: false
repos:
-   repo: local
    hooks:
      - id: isort
        args:
            - --check-only
        name: isort
        entry: isort
        language: system
        types: [python]

-   repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v1.4.0
    hooks:
    -   id: debug-statements
    -   id: end-of-file-fixer
    -   id: flake8
        include: (src|tests)
        args:
        - src/
        - tests/
    -   id: check-merge-conflict
    -   id: check-case-conflict
